### ISSUE TITLE
Files not Git Repos; Files not Found when try to open repo link

### ISSUE THREAD

**Issue by yanakog** [mumt301/ykogan#1]
Transferring files into the /Github/ykogan folder doesn't seem to work like it did during class... When I copy files over there and try to put them into GitHub an error pops up, but the files still seem to get added. When I open up my link to the repo, it states that files aren't found.

**Comment by martha-thomae** [comment]
Have you push your changes?
When does it fail, at the moment of making the commit? or at the moment of pushing?

You can send a screenshot to check it out.

**Comment by yanakog** [comment]
![image](https://user-images.githubusercontent.com/71049392/93618846-d2d02d80-f9a5-11ea-9443-9b6d43d7dfab.png)

I did push them previously! Now when I try re-adding them I get this error. Could there be an issue due to file names? I previously had an Index.html file from class, but I renamed it to index1.html. I then uploaded the index.html file I wanted to use for my assignment.

When I open Github now I only have the two files from class.

**Comment by yanakog** [comment]
![image](https://user-images.githubusercontent.com/71049392/93619345-70c3f800-f9a6-11ea-8faf-ca9e48ca9fe6.png)

Here is my history

**Comment by martha-thomae** [comment]
It is difficult for me to say what is wrong based just on the screenshots. Would you mind dropping by the office hours of the TA? Or making an appointment with us?

You are just editing (or renaming) your files and then GitHub Desktop automatically detect those changes and shows them to you, right? (not dragging anything into the app?)

----

In the mean time, what you could do just to quickly solve this is:
- copy the files you modify somewhere else on your computer (so that you don't lose your changes)
- remove the local copy of your repo
- clone it again
- make the changes (paste the content of your old files)
- and commit and push again

I would prefer to see it to be able to check what could have caused this, but if you want to solve it quickly you could just clone it again and make the changes.

**Comment by martha-thomae** [comment]
> ![image](https://user-images.githubusercontent.com/71049392/93618846-d2d02d80-f9a5-11ea-9443-9b6d43d7dfab.png)
> 
> I did push them previously! Now when I try re-adding them I get this error. Could there be an issue due to file names? I previously had an Index.html file from class, but I renamed it to index1.html. I then uploaded the index.html file I wanted to use for my assignment.

Normally when you rename a file, GitHub Desktop app would show that as if you had removed one file (with the old filename) and add a new one (with the new filename), like this:

![rename](https://user-images.githubusercontent.com/13948831/93648216-3d9a5c80-f9d8-11ea-9651-129ccf2fb0c0.png)

That is before you commit and push it to GitHub. After that, it looks like this in your history:

![rename-in-history](https://user-images.githubusercontent.com/13948831/93648294-70445500-f9d8-11ea-930a-bd014baff525.png)

---

> When I open Github now I only have the two files from class.

I see in your [GitHub repo](https://github.com/mumt301/ykogan) the two files from the class plus the 'assignments.html' file. So everything seemed to be pushed correctly until that last change you were trying to make. Do you mean that 'assignments.html' is no longer in your local copy of the repository, in your computer?

**Comment by yanakog** [comment]
I talked to Yuval about it yesterday during his OH. I figured out my previous concerns with updating the files, and as you've mentioned they seem to have been pushed properly, but the link still opens up as an error and "Files not found". Not quite sure what to do about that

**Comment by martha-thomae** [comment]
Have you activated your GitHub Pages?
It is in Settings, and then go to GitHub Pages. You have to put "master" as your "source" and save. Otherwise, you won't have GitHub Pages activated so you won't be able to see anything in [https://mumt301.github.io/ykogan](https://mumt301.github.io/ykogan).

**Comment by yanakog** [comment]
I must have forgotten to save the change, thank you! That seems to have fixed it! But it does say that Github Pages is down for maintenance at the moment

**Comment by martha-thomae** [comment]
You are welcome!
Don't worry, sometimes it takes a few minutes to update.

**Comment by napulen** [comment]
I can say that the page is rendering fine on my browser :tada:
